### ISSUE TITLE
how to pipe in files or messages in general

### ISSUE THREAD

**Issue by elisehuard** [ryane/docker-kafkacat#1]
Hi, thanks for dockerizing kafkacat.  Just wondered how you pipe input into it?  the process doesn't have access to stdin or local files, obviously, unless you do a song-and-dance to have it access local volumes.  Any tips?

**Comment by ryane** [comment]
Hi @elisehuard. tbh, I built this for a demo on a test kafka cluster so I am far from an expert on it. But, here is an example of piping input into it:

`sudo journalctl -f | sudo docker run --rm -i ryane/kafkacat -b broker-0.service.consul:4002 -t journal -z snappy`

**Comment by elisehuard** [comment]
thank you!
